# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := 04_camera-app

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

04_camera-app: 
	@echo "==== Building 04_camera-app ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f 04_camera-app.make

clean:
	@${MAKE} --no-print-directory -C . -f 04_camera-app.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   04_camera-app"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
